[PIN-2354] Adapted calls using tenant-management/process
pagopa/interop-be-api-gateway pull request #130
Opened 2022-11-25 10:58 UTC by bloodsky

2022-11-25 16:19 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/apigateway/api/impl/GatewayApiServiceImpl.scala
> +      .upsertTenant(m2mTenantSeedFromApi(origin, externalId, "Waiting for IPA")(code))
Which is the field you filled with `"Waiting for IPA"`?

2022-11-25 16:20 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/apigateway/api/impl/GatewayApiServiceImpl.scala
> +      .upsertTenant(m2mTenantSeedFromApi(origin, externalId, "Waiting for IPA")(code))
NVM, is `name`, I saw it later, sorry

2022-11-25 16:21 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/apigateway/api/impl/GatewayApiServiceImpl.scala
>      )
Add a space between methods/functions/expressions. I fear that your ide might be misconfigured, check if the formatter is `scalafmt`

2022-11-25 16:22 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/apigateway/api/impl/package.scala
> +    def toModel(category: String): Organization = {
Useless parenthesis

2022-11-25 16:22 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/apigateway/server/impl/Dependencies.scala
> +        // partyManagementService(),
🧹

2022-11-25 16:22 UTC, TonioGela requested changes
LGTM, but I asked for a few changes

2022-11-28 11:57 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/apigateway/service/impl/PartyRegistryProxyServiceImpl.scala
> +      // xCorrelationId = correlationId,
🧹

2022-11-28 11:57 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/apigateway/service/impl/PartyRegistryProxyServiceImpl.scala
> +      // xForwardedFor = ip
🧹

2022-11-28 11:57 UTC, TonioGela approved these changes

2022-11-28 11:59 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/apigateway/service/impl/PartyRegistryProxyServiceImpl.scala
> +      // xCorrelationId = correlationId,
Nope, once [this](https://github.com/pagopa/interop-be-party-registry-proxy/pull/144) gets merged you need to add these params

2022-11-30 07:55 UTC, beetlecrunch approved these changes

2022-12-01 10:04 UTC, galales approved these changes

2022-12-05 11:51 UTC, merged